Update 1.yml

diff --git a/.github/workflows/1.yml b/.github/workflows/1.yml
--- a/.github/workflows/1.yml
+++ b/.github/workflows/1.yml
@@ -1,26 +1,33 @@
 name: Manual Run Test
 
 on:
-  workflow_dispatch:  # 允许手动触发工作流
+  workflow_dispatch:
 
 jobs:
   run-test:
-    runs-on: ubuntu-latest  # 设置运行环境为 Ubuntu
+    runs-on: ubuntu-latest
 
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2  # 检出代码库的内容
+        uses: actions/checkout@v2
 
       - name: Set up Node.js
         uses: actions/setup-node@v2
         with:
-          node-version: '14'  # 设置 Node.js 版本为 14
+          node-version: '14'
 
       - name: Download package.json
-        run: curl -o package.json https://github.com/Script-Hub-Org/Script-Hub/raw/main/package.json
+        run: wget https://github.com/Script-Hub-Org/Script-Hub/raw/main/package.json -O package.json
+
+      - name: Check if package.json exists and is not empty
+        run: |
+          if [ ! -s package.json ]; then
+            echo "package.json is missing or empty!"
+            exit 1
+          fi
 
       - name: Install dependencies
-        run: npm install  # 安装项目依赖
+        run: npm install
 
       - name: Run Test Script
-        run: node Scripts/Test.js  # 运行指定的测试脚本
+        run: node Scripts/Test.js
